Running window extended to builtin windows and some refactors
synnada-ai/arrow-datafusion pull request #10
Opened 2022-10-27 06:27 UTC by mustafasrepo

# Which issue does this PR close?

Closes #.

 # Rationale for this change

# What changes are included in this PR?

# Are there any user-facing changes?

2022-10-28 21:12 UTC, ozankabak requested changes
Let's go through my initial reviews, I will review again after.

2022-10-28 21:12 UTC, ozankabak commented on datafusion/physical-expr/src/window/aggregate.rs
> +                Some(Arc::new(WindowFrame {
Would `WindowFrame::default()` work here?

2022-10-28 21:12 UTC, ozankabak commented on datafusion/physical-expr/src/window/aggregate.rs
> +                // let mut accumulator = self.aggregate.create_accumulator()?;
Possible leftover from debugging, remove.

2022-10-28 21:12 UTC, ozankabak commented on datafusion/physical-expr/src/window/aggregate.rs
> +                    // println!("cur range: {:?}", cur_range);
Possible leftover from debugging, remove.

2022-10-28 21:12 UTC, ozankabak commented on datafusion/physical-expr/src/window/built_in.rs
> +                        Some(Arc::new(WindowFrame {
Would `WindowFrame::default()` work here?

2022-10-28 21:12 UTC, ozankabak commented on datafusion/physical-expr/src/window/built_in.rs
> +                    &order_columns[self.partition_by.len()..order_columns.len()].to_vec();
Can we just use:
```rust
let order_bys = &order_columns[self.partition_by.len()..].to_vec();
```

2022-10-28 21:12 UTC, ozankabak commented on datafusion/physical-expr/src/window/aggregate.rs
> +            &order_columns[self.partition_by.len()..order_columns.len()].to_vec();
Can we just use:
```rust
let order_bys = &order_columns[self.partition_by.len()..].to_vec();
```

2022-10-28 21:12 UTC, ozankabak commented on datafusion/physical-expr/src/window/built_in.rs
> +                    .map(|elem| evaluator.evaluate_inside_range(elem.clone()).unwrap())
Do we have a guarantee that the `unwrap` call will not fail?

2022-10-28 21:12 UTC, ozankabak commented on datafusion/physical-expr/src/window/nth_value.rs
>                  let index = (n as usize) - 1;
Is `n = 0` a possible case here? If so, does the code still work?

2022-10-30 07:58 UTC, mustafasrepo commented on datafusion/physical-expr/src/window/nth_value.rs
>                  let index = (n as usize) - 1;
Postgre expects nth_value argument to be larger than 0 according to [this link](https://www.postgresql.org/docs/current/functions-window.html). I have tried the nth_value(0) query on dbfiddle it gave  

> Query Error: error: argument of nth_value must be greater than zero

In datafusion nth_value(0) case raises [an error](https://github.com/apache/arrow-datafusion/blob/71f05a3175e931943276a8778162e37504e00503/datafusion/physical-expr/src/window/nth_value.rs#L89) also
I have added a comment also saying `// We are certain that n > 0`

2022-10-30 08:00 UTC, mustafasrepo commented on datafusion/physical-expr/src/window/built_in.rs
> +                    .map(|elem| evaluator.evaluate_inside_range(elem.clone()).unwrap())
I have removed unwrap

2022-10-31 07:01 UTC, ozankabak approved these changes

2022-10-31 07:10 UTC, ozankabak approved these changes
LGTM. I sent a few simplifying changes too. I don't fully understand one comment (for which I left a review), apart from that -- looks good.

About that specific comment: Isn't iterating on all rows just to calculate frame boundaries very inefficient? Is this really what we do (and what you mean)? Let's clarify this, and if there is anything to fix/improve, fix it. Otherwise, we can just make the comment clearer, compose a PR body, and create an upstream PR to get community review.

2022-10-31 07:10 UTC, ozankabak commented on datafusion/physical-expr/src/window/built_in.rs
> +                // We iterate on each row to calculate window frame boundaries
Is this comment accurate?

2022-10-31 07:52 UTC, ozankabak commented on datafusion/physical-expr/src/window/partition_evaluator.rs
> +    /// evaluate the partition evaluator against the partition but with rank
This comment is the same with the one above. This function needs its own comment.

2022-11-02 06:44 UTC, mustafasrepo commented on datafusion/physical-expr/src/window/partition_evaluator.rs
> +    /// evaluate the partition evaluator against the partition but with rank
Changed comment

2022-11-02 06:49 UTC, mustafasrepo commented on datafusion/physical-expr/src/window/built_in.rs
> +                // We iterate on each row to calculate window frame boundaries
Changed the comment to make it more clear

2022-11-05 11:48 UTC, ozankabak commented
Closing as this merged upstream.

2022-11-05 11:48 UTC, closed without merging