Replace OrderedColumn with PhysicalSortExpr
synnada-ai/arrow-datafusion pull request #110
Opened 2023-05-26 12:21 UTC by mustafasrepo

# Which issue does this PR close?

Closes #.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

2023-05-27 21:55 UTC, ozankabak requested changes
This will benefit from the changes we are making in the multiple-with-order PR. For example, that PR defines the `LexOrdering` type in `core/src/physical_plan/file_format/mod.rs` and exposes it within the crate. This PR redefines the same type.

Let's rebase this on of that PR, remove the conflicts and move such commonalities to appropriate places to improve the code structure. I will do the more in-depth review afterwards.

2023-05-27 22:11 UTC, ozankabak commented on datafusion/physical-expr/src/equivalence.rs
> +        // If the the removed entry is head, shit other such that first entry becomes head in others.
```suggestion
        // If we are removing the head, shift others so that its first entry becomes the new head.
```

2023-05-30 21:15 UTC, ozankabak commented
Let's resolve the conflict, write PR body and open it upstream.

2023-06-07 06:51 UTC, mustafasrepo commented
Merged upstream

2023-06-07 06:51 UTC, closed without merging