Resolve contradictory requirements by conversion of ordering sensitive aggregators
synnada-ai/arrow-datafusion pull request #111
Opened 2023-05-27 14:32 UTC by mustafasrepo

# Which issue does this PR close?

Closes #.

# Rationale for this change

# What changes are included in this PR?

# Are these changes tested?

# Are there any user-facing changes?

2023-05-27 22:43 UTC, ozankabak requested changes
Please check out the two in-line comments I left. Other than those, I see that this PR will benefit from having `LexOrdering` at a central place too (like your other PR). Let's make sure this is compatible with that PR in that sense.

It looks good to me other than these minor points.

2023-05-27 22:43 UTC, ozankabak commented on datafusion/core/src/physical_plan/aggregates/mod.rs
> +        // such as when all ordering sensitive aggregate expressions are either FIRST_VALUE, LAST_VALUE)
This comment is unclear, let's clarify.

2023-05-27 22:43 UTC, ozankabak commented on datafusion/core/src/physical_plan/aggregates/mod.rs
> +            if idx == 1 {
The code structure is confusing. Is it possible for `aggregator_requirements` to have more than two elements, or is it strictly a two-element collection at this point? It is not clear what makes `idx == 1` special.

I also see that you don't seem to make any changes to `aggr_expr` beyond the `idx == 1`, but this is still inside the loop where you are deciding `required_input_ordering`.

All of these make think there should be a better way to express your algorithm. Please think about a refactor.

2023-05-30 07:51 UTC, mustafasrepo commented on datafusion/core/tests/sqllogictests/test_files/groupby.slt
> +0 0 24
Since ordering requirement column `a` is inside the group by expressions. Both results are valid. However, with the changes in this PR result changes.

2023-05-30 07:51 UTC, mustafasrepo commented on datafusion/core/tests/sqllogictests/test_files/groupby.slt
> +0 0 0
Similar to above case.

2023-06-03 06:35 UTC, mustafasrepo commented
Merged upstream

2023-06-03 06:35 UTC, closed without merging