Support multiple ordered columns on joins and expresion graph.
synnada-ai/arrow-datafusion pull request #163
Opened 2023-08-10 15:33 UTC by metesynnada

## Which issue does this PR close?

Closes #.

## Rationale for this change

## What changes are included in this PR?

## Are these changes tested?

## Are there any user-facing changes?

2023-08-18 11:27 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +                // println!("converted_filter_expr {}", converted_filter_expr);
leftover

2023-08-18 11:34 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +        .collect::<Vec<_>>();
```rust
        .collect::<Result<Vec<_>>>()?
        .into_iter()
        .flatten()
        .collect();
```
you can replace with code above

2023-08-18 12:01 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +/// // TODO: Change the docstring
There is a TODO here. it can be leftover

2023-08-18 12:07 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/sliding_window_join_utils.rs
> +        .collect::<Vec<_>>();
`        .collect::<Result<Vec<_>>>()?;`

2023-08-18 12:08 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/sliding_window_join_utils.rs
> +        .all(|b| b))
```rust
    Ok(result
        .into_iter()
        .all(|b| b))
```

2023-08-18 12:10 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/sliding_window_join_utils.rs
> +            })
```rust
            Ok(if sorted_shrunk_expr.options.descending{
                // Data is sorted in descending order, so check if latest value is less
                // than the lower bound of the interval. If it is, we must have processed
                // all rows that are needed from the build side for this window.
                latest_value < interval.lower.value
            } else{
                // Data is sorted in ascending order, so check if latest value is greater
                // than the upper bound of the interval. If it is, we must have processed
                // all rows that are needed from the build side for this window.
                latest_value > interval.upper.value
            })
```

2023-08-18 12:11 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/sliding_window_join_utils.rs
> +        .collect::<Vec<_>>();
`.collect::<Result<Vec<_>>>()?;`

2023-08-18 12:12 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/sliding_window_join_utils.rs
> +        .all(|e| *e))
```rust
    Ok(results
        .iter()
        .all(|e| *e))
```

2023-08-18 15:02 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/utils.rs
> +                        let sa = Arc::new(Column::new_with_schema(
maybe this variable name can be changed

2023-08-18 15:02 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/utils.rs
> +        // println!("prune_length {}", prune_length);
leftover

2023-08-18 15:02 UTC, mustafasrepo commented on datafusion/core/src/physical_plan/joins/utils.rs
> +        // println!("prune_length {}", 0);
left over print

2023-08-18 15:03 UTC, mustafasrepo commented on datafusion/physical-expr/src/expressions/cast.rs
> +    fn get_ordering(&self, _children: &[ExtendedSortOptions]) -> ExtendedSortOptions {
variable can children instead of _children since it is used

2023-08-25 01:23 UTC, ozankabak requested changes
Even though they are mostly small things, there are a lot of things to address here. Please go over all the comments (mine and Mustafa's remaining ones) and address all of them.

I will then do one last check and this will be ready after you write a PR body.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +use datafusion_common::utils::bisect;
Let's move these next to other `datafusion` imports so it is easy to see what is imported in one look

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +/// Returns a [SchemaRef] representing the schema of the filter for the build side.
```suggestion
/// This function generates a [`SchemaRef`] with fields from the build side that are used
/// in the join filter. The resulting [`SchemaRef`] can be used for creating a
/// filter representation [`RecordBatch`].
///
/// # Arguments
///
/// * `filter_schema` - The [`Schema`] of the join filter.
/// * `column_indices` - The indices of the columns used in the join filter.
/// * `build_side` - The side of the join that is being built.
///
/// # Returns
///
/// Returns a [`SchemaRef`] representing the schema of the filter for the build side.
```

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +/// Returns a [RecordBatch] representing the filter of the build side.
```suggestion
/// This function generates a [`RecordBatch`] with columns from the build side that are used
/// in the join filter. The resulting [`RecordBatch`] can be used for further filtering
/// or pruning operations.
///
/// # Arguments
///
/// * `filter_schema` - The [`Schema`] of the join filter.
/// * `build_inner_buffer` - The [`RecordBatch`] on the build side of the join.
/// * `column_indices` - The indices of the columns used in the join filter.
/// * `build_side` - The side of the join that is being built.
///
/// # Returns
///
/// Returns a [`RecordBatch`] representing the filter of the build side.
```

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +/// Return type for prepare_sorted_exprs method
Let's write a better comment explaining what this type is and how it is used.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +                        let sa = Arc::new(Column::new_with_schema(
Yes, please change this variable name.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +pub(crate) fn calculate_prune_length_with_probe_batch_helper(
This function needs a docstring explaining what it does, its arguments, return value etc.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +pub(crate) fn get_build_side_pruned_exprs(
This function needs a docstring explaining what it does, its arguments, return value etc.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +        .collect::<Vec<(PhysicalSortExpr, Interval)>>()
```suggestion
        .collect()
```

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +/// A [Result] object that contains the pruning length. The function will return
```suggestion
/// A [`Result`] object that contains the pruning length. The function will return
```

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +    }
```suggestion
    Ok(prune_lengths.into_iter().min().unwrap_or(0))
```

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/symmetric_hash_join.rs
> +use crate::physical_plan::joins::utils::prepare_sorted_exprs;
Let's move these next to other crate imports above.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/symmetric_hash_join.rs
>  use datafusion_common::{DataFusionError, Result};
Let's join these in a single line.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/symmetric_hash_join.rs
> +            )));
I think upstream prefers macros like `internal_err`, let's use them whenever possible.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +    for class in order_classes {
```suggestion
    for class in ordering_equivalence_properties.classes() {
```

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +    let mut temp_sort_exprs = vec![];
Maybe `additional_sort_exprs` is a better name for this variable?

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +            for class in eq_classes {
```suggestion
            for class in equivalence_properties.classes() {
```

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +                    temp_sort_exprs.extend(sort_exprs)
You probably don't need to collect above, `extend` should be able to take in an iterator.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +                                let sa = Arc::new(Column::new_with_schema(
Please change the variable name unless `sa` is a meaningful shortcut in this context.

2023-08-25 01:23 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/hash_join_utils.rs
> +/// // TODO: Change the docstring
If this is indeed a leftover, let's remove. Otherwise, let's make sure to update the docstring appropriately.

2023-09-05 11:13 UTC, ozankabak approved these changes
Almost done. Please address the 6 comments I left and we can merge this to our fork.

2023-09-05 11:13 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +pub(crate) fn calculate_prune_length_with_probe_batch_helper(
Let's write a docstring.

2023-09-05 11:13 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
>  pub fn prepare_sorted_exprs(
Docstring is out of date, let's update it so that it has all the arguments and has an accurate explanation.

2023-09-05 11:13 UTC, ozankabak commented on datafusion/core/src/physical_plan/joins/utils.rs
> +pub type SortedFilterInformation = (
Let's write a better comment explaining what this type is and how it is used.

2023-09-05 11:13 UTC, ozankabak commented on datafusion/physical-expr/src/intervals/cp_solver.rs
> +    pub fn get_smallest_pruning_exprs(
Let's write a docstring.

2023-09-05 11:13 UTC, ozankabak commented on datafusion/physical-expr/src/intervals/cp_solver.rs
> +    pub fn assign_sort_information(&mut self, sorted_exprs: &[PhysicalSortExpr]) {
Let's write a docstring.

2023-09-05 13:55 UTC, merged