initial iteration for Kafka sink
synnada-ai/arrow-datafusion pull request #40
Opened 2023-01-20 10:00 UTC by lazerion

## Initial commit for Kafka Sink

- Introduces new package as `datafusion-sinks`

### Completed

- [x] Basic API exposure for Sink abstraction
- [x] PoC implementation for Kafka
- [x] Json Serializer for encoding `Event` 
- [x] Basic integration tests on single partition

### Next Steps
- [ ] Filing issues based on reviews
- [ ] Source code and README documentations

### Reference Projects
- Kafka Client [rust-rdkafka](https://github.com/fede1024/rust-rdkafka)

2023-01-20 10:02 UTC, lazerion commented on datafusion/sinks/src/api.rs
> +    async fn run(self: Box<Self>, input: Event) -> Result<(), Error>;
Currently support as single `Event` dispatch in async. manner.
I believe that `Stream` of dispatch should be supported. 
Please LMK I will be creating follow up issue based on tokio stream.

2023-01-20 10:05 UTC, lazerion commented on datafusion/sinks/src/codecs/json.rs
> +pub struct JsonSerializerConfig {}
Currently empty on purpose, as at this I need guidance on whether we would need `required schema` or not, or any other user defined configurations for serializations.

2023-01-20 10:08 UTC, lazerion commented on datafusion/sinks/src/kafka/config.rs
> +pub struct KafkaSinkConfig {
It will be extended with below, based on review feedback in different issues. Therefore, it would be good if we get priorities on them.
- compression
- auth.

2023-01-20 10:12 UTC, lazerion commented on datafusion/sinks/src/kafka/request.rs
> +impl KafkaRequestBuilder {
It will be extended with `metadata` for Kafka request to back payload data. Not sure, if it is needed atm.

2023-01-20 10:14 UTC, lazerion commented on datafusion/sinks/src/kafka/service.rs
> +impl Service<KafkaRequest> for KafkaService {
After digging deeper into Datafusion side, this service would probably be extended with `Notification` with a `mpsc` channel.

2023-01-20 10:17 UTC, lazerion commented on datafusion/sinks/src/lib.rs
> +    Aggregation(AggregationData),
Just a sample event type for the PoC purposes. I would appreciate guidance on Datafusion core process side to model proper event type. Crucial part would be a `key field` approach to have ordered events in Kafka partitions.

2023-01-20 10:19 UTC, lazerion commented on datafusion/sinks/tests/integration_test.rs
> +#[ignore]
IT tests currently ignored as I could not catch a docker file based test runner, please LMK or guide on this to add this integration test based on `kafka-service.yaml`.
Yet, you can run these tests, after `docker-compose -f kafka-service.yaml` up.

2023-02-09 08:13 UTC, metesynnada commented on datafusion/sinks/src/lib.rs
> +    Aggregation(AggregationData),
I consider a future stream with the `RecordBatch` item. In the Datafusion context, a RecordBatch stream would be consumed. 

Thus, we need a `RecordBatch` serializer as well. Maybe arrow-csv, arrow-json, etc. libraries have a sensible way to do that. However, they are not async libraries. Maybe first, we should figure out async serialization methods.

I suggest that we need to contribute the `arrow-csv` and others to make async serialization. 
- There are a lot of util functions in `arrow-csv` and others, and we need to exploit them. E.g  `convert` of `impl<W: Write> Writer<W>`.
- We need async serialize of `RecordBatch` es as well. KafkaRequestBuilder actually needs to return a future stream (outputs requests) or a request future.

2023-02-09 08:37 UTC, metesynnada requested changes
My main focus is making the sink (and source) async as much as possible. I suggest you look into 
- `pub type SendableRecordBatchStream = Pin<Box<dyn RecordBatchStream + Send>>;` type, since we would support that.
- Record batch serialization: E.g  `convert` of `impl<W: Write> Writer<W>`.
My other suggestions are inside the code, thanks for your effort.

2023-02-09 08:37 UTC, metesynnada commented on datafusion/sinks/src/kafka/config.rs
> +    fn health_check(&self) -> HealthCheck {
I think this may belong to the service, not the config.

2023-02-09 08:37 UTC, metesynnada commented on datafusion/sinks/src/kafka/request.rs
> +    pub fn build_request(&mut self, event: Event) -> Option<KafkaRequest> {
I think we can further improve this part. I believe that `KafkaRequestBuilder` can be responsible for request stream building. Async nature must be preserved here as well since this part would consume a `futures::stream`.

2023-02-09 08:37 UTC, metesynnada commented on datafusion/sinks/src/kafka/request.rs
> +    fn get_key(&self, event: &Event) -> Option<Bytes> {
We can discuss with @ozankabak that key is a part of partitioning process. But I think this is also part of the `RepartitionExec` logic of the output of the execution plan. 

- If the output of execution plan is `HashPartition(some_key)`, we can put corresponding key. However, we would add data globally since the hash function would different in Datafusion and Kafka.

- If the output of execution plan is `UnknownPartition` or `RoundRobin`, we would not put a key for Kafka records. If planner output partition count equals kafka topic count, we would insert data "datafusion partition to kafka partition", else "datafusion partition to global without key" (different).
- If the output of execution plan is `SinglePartition`, we would insert data globally without any key information.

2023-02-09 08:37 UTC, metesynnada commented on datafusion/sinks/src/kafka/service.rs
> +impl Service<KafkaRequest> for KafkaService {
I am not sure notification part, however aborting is possible with channel messages, as you mentioned.

2023-02-09 08:37 UTC, metesynnada commented on datafusion/sinks/src/kafka/service.rs
> +    fn call(&mut self, request: KafkaRequest) -> Self::Future {
The async logic is quite good in this part, let's make it more performant with `future::stream of RecordBatch`.

2023-02-09 08:37 UTC, metesynnada commented on datafusion/sinks/src/kafka/sink.rs
> +pub(crate) async fn health_check(config: KafkaSinkConfig) -> crate::Result<()> {
We can use config here, but this can be accessed from the service since this will be a periodic async call. Client creation for each call is not necessary.

2023-06-26 20:16 UTC, ozankabak commented
Converting to draft until it matures.

2023-12-08 21:27 UTC, ozankabak commented
This feature will be available via the `StreamTable` mechanism.

2023-12-08 21:27 UTC, closed without merging